# Generated by Django 4.2.2 on 2023-06-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('data_criacao', models.DateField()),
                ('imagem', models.ImageField(upload_to='imagens')),
            ],
        ),
        migrations.DeleteModel(
            name='Alimentos',
        ),
        migrations.DeleteModel(
            name='Apicultura',
        ),
        migrations.DeleteModel(
            name='Informatica',
        ),
    ]
