# Generated by Django 4.2.2 on 2023-06-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_delete_alimentos_delete_apicultura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='data_criacao',
            new_name='data_de_criacao',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='titulo',
        ),
        migrations.AddField(
            model_name='curso',
            name='nome_do_curso',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
